name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.3'  # Usando Ruby 3.3.3

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Prepare database
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate

    - name: Run tests
      run: bundle exec rake test
