name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.3'
    - name: Install dependencies
      run: |
        echo 'GEM_HOME=$HOME/.gem' >> $GITHUB_ENV
        echo 'PATH=$HOME/.gem/bin:$PATH' >> $GITHUB_ENV
        gem install bundler
        bundle install
    - name: Adjust permissions
      run: |
        chmod +x bin/rails
    - name: Set up database
      run: |
        bundle exec rails db:setup
    - name: Run migrations
      run: |
        bundle exec rails db:migrate
    - name: Run tests
      run: |
        bundle exec rake test
    - name: Deploy
      run: |
        rsync -avz --delete-after ./ meu-servidor:/caminho/do/deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
