name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: bundle exec rake test
    - name: Deploy
      run: |
        rsync -avz --delete-after ./ meu-servidor:/caminho/do/deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
