name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.3'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Add Ruby to PATH
      run: echo 'export PATH="/opt/hostedtoolcache/Ruby/3.3.3/x64/bin:$PATH"' >> $GITHUB_ENV
    - name: Adjust permissions
      run: |
        chmod +x bin/rails
    - name: Set up database
      run: |
        bin/rails db:setup
    - name: Run migrations
      run: |
        bin/rails db:migrate
    - name: Run tests
      run: |
        bundle exec rake test
    - name: Deploy
      run: |
        rsync -avz --delete-after ./ meu-servidor:/caminho/do/deploy/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
